"""Add current_level to User model

Revision ID: caf82979cb8b
Revises: da0be4004a53
Create Date: 2025-08-05 12:35:19.911665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf82979cb8b'
down_revision: Union[str, Sequence[str], None] = 'da0be4004a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # 1. Kolonu, varsayılan bir sunucu değeriyle ve boş olabilir olarak ekle
        batch_op.add_column(sa.Column('current_level', sa.String(), nullable=True, server_default='A1'))

    # 2. Mevcut tüm satırları 'A1' değeriyle güncelle (eğer server_default çalışmazsa garanti olsun diye)
    op.execute("UPDATE users SET current_level = 'A1' WHERE current_level IS NULL")

    with op.batch_alter_table('users', schema=None) as batch_op:
        # 3. Artık tüm satırlar dolu olduğuna göre, kolonu NOT NULL yap
        batch_op.alter_column('current_level',
               existing_type=sa.String(),
               nullable=False,
               server_default=None) # server_default'u artık kaldırabiliriz
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('current_level')
    # ### end Alembic commands ###